name: forestvision

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - earthengine-api
  - geopandas
  - kornia
  - matplotlib
  - numpy
  - pandas
  - python=3.10
  - pytorch=2.2.2
  - pytorch-cuda=11.8
  - torchvision==0.17.2
  - lightning[all]
  - rasterio
  - rio-cogeo
  - scikit-learn
  - shapely
  - torchmetrics 
  - tqdm
  - pip
  - pip:
      - torchgeo[all]
