[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "forestvision"
version = "0.1.0"
authors = [
    {name = "Yankuic Galvan", email = "yankuic@gmail.com"},
]
description = "Machine learning package for forest analysis from remote sensing data"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.11"
dependencies = [
    "earthengine-api",
    "geopandas",
    "kornia",
    "torch>=2.5.1",
    "torchvision>=0.20.1",
    "lightning[all]",
    "torchgeo[all]",
    "rasterio",
    "scikit-learn",
    "numpy",
    "pandas",
    "matplotlib",
    "shapely>=2.0",
    "torchmetrics",
    "tqdm",
    "dotenv",
    "retry",
    "requests",
    "rio_cogeo",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: GIS",
]

[project.urls]
Homepage = "https://github.com/ygalvan/forestvision"

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "flake8",
    "mypy",
    "sphinx",
]
notebooks = [
    "jupyter",
    "geemap",
    "folium",
]

[tool.black]
line-length = 88
target-version = ['py311']
